# Generated by Django 2.1.7 on 2019-02-16 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190216_2244'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermessage',
            table=None,
        ),
    ]
