# Generated by Django 2.1.7 on 2019-02-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_auto_20190216_2246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
